# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='route.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0broute.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x1f\n\rHistoryLength\x12\x0e\n\x06Length\x18\x01 \x01(\x05\"\x1b\n\nTimeSeries\x12\r\n\x05Value\x18\x01 \x03(\x02\"\"\n\x07History\x12\x17\n\x02TS\x18\x01 \x03(\x0b\x32\x0b.TimeSeries\"\x12\n\x03Tmp\x12\x0b\n\x03tmp\x18\x01 \x01(\x05\"j\n\tSelection\x12\r\n\x05\x41sset\x18\x01 \x01(\t\x12\x10\n\x08Strategy\x18\x02 \x01(\t\x12+\n\nParameters\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0f\n\x07\x43\x61pital\x18\x04 \x01(\x05\"\xed\x01\n\nStatistics\x12\t\n\x01v\x18\x01 \x01(\x02\x12\t\n\x01t\x18\x02 \x01(\x02\x12\t\n\x01o\x18\x03 \x01(\x02\x12\t\n\x01h\x18\x04 \x01(\x02\x12\t\n\x01l\x18\x05 \x01(\x02\x12\t\n\x01\x63\x18\x06 \x01(\x02\x12\x0e\n\x06\x61\x63tion\x18\x07 \x01(\x02\x12\x16\n\x0e\x62\x61lance_change\x18\x08 \x01(\x02\x12\r\n\x05stock\x18\t \x01(\x02\x12\x0f\n\x07\x62\x61lance\x18\n \x01(\x02\x12\x0e\n\x06return\x18\x0b \x01(\x02\x12\r\n\x05\x61lpha\x18\x0c \x01(\x02\x12\x0e\n\x06sharpe\x18\r \x01(\x02\x12\x15\n\rannual_sharpe\x18\x0e \x01(\x02\x12\x0f\n\x07sortino\x18\x0f \x01(\x02\x32\x89\x01\n\x05Route\x12\x30\n\x13InitialiseAlgorithm\x12\n.Selection\x1a\x0b.Statistics\"\x00\x12$\n\rGetStatistics\x12\x04.Tmp\x1a\x0b.Statistics\"\x00\x12(\n\nGetHistory\x12\x0e.HistoryLength\x1a\x08.History\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_HISTORYLENGTH = _descriptor.Descriptor(
  name='HistoryLength',
  full_name='HistoryLength',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Length', full_name='HistoryLength.Length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=76,
)


_TIMESERIES = _descriptor.Descriptor(
  name='TimeSeries',
  full_name='TimeSeries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Value', full_name='TimeSeries.Value', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=105,
)


_HISTORY = _descriptor.Descriptor(
  name='History',
  full_name='History',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TS', full_name='History.TS', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=141,
)


_TMP = _descriptor.Descriptor(
  name='Tmp',
  full_name='Tmp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tmp', full_name='Tmp.tmp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=161,
)


_SELECTION = _descriptor.Descriptor(
  name='Selection',
  full_name='Selection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Asset', full_name='Selection.Asset', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Strategy', full_name='Selection.Strategy', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Parameters', full_name='Selection.Parameters', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Capital', full_name='Selection.Capital', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=269,
)


_STATISTICS = _descriptor.Descriptor(
  name='Statistics',
  full_name='Statistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v', full_name='Statistics.v', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t', full_name='Statistics.t', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='o', full_name='Statistics.o', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='Statistics.h', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='l', full_name='Statistics.l', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c', full_name='Statistics.c', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='Statistics.action', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance_change', full_name='Statistics.balance_change', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stock', full_name='Statistics.stock', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='Statistics.balance', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return', full_name='Statistics.return', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='Statistics.alpha', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sharpe', full_name='Statistics.sharpe', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='annual_sharpe', full_name='Statistics.annual_sharpe', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sortino', full_name='Statistics.sortino', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=509,
)

_HISTORY.fields_by_name['TS'].message_type = _TIMESERIES
_SELECTION.fields_by_name['Parameters'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['HistoryLength'] = _HISTORYLENGTH
DESCRIPTOR.message_types_by_name['TimeSeries'] = _TIMESERIES
DESCRIPTOR.message_types_by_name['History'] = _HISTORY
DESCRIPTOR.message_types_by_name['Tmp'] = _TMP
DESCRIPTOR.message_types_by_name['Selection'] = _SELECTION
DESCRIPTOR.message_types_by_name['Statistics'] = _STATISTICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HistoryLength = _reflection.GeneratedProtocolMessageType('HistoryLength', (_message.Message,), {
  'DESCRIPTOR' : _HISTORYLENGTH,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:HistoryLength)
  })
_sym_db.RegisterMessage(HistoryLength)

TimeSeries = _reflection.GeneratedProtocolMessageType('TimeSeries', (_message.Message,), {
  'DESCRIPTOR' : _TIMESERIES,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:TimeSeries)
  })
_sym_db.RegisterMessage(TimeSeries)

History = _reflection.GeneratedProtocolMessageType('History', (_message.Message,), {
  'DESCRIPTOR' : _HISTORY,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:History)
  })
_sym_db.RegisterMessage(History)

Tmp = _reflection.GeneratedProtocolMessageType('Tmp', (_message.Message,), {
  'DESCRIPTOR' : _TMP,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:Tmp)
  })
_sym_db.RegisterMessage(Tmp)

Selection = _reflection.GeneratedProtocolMessageType('Selection', (_message.Message,), {
  'DESCRIPTOR' : _SELECTION,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:Selection)
  })
_sym_db.RegisterMessage(Selection)

Statistics = _reflection.GeneratedProtocolMessageType('Statistics', (_message.Message,), {
  'DESCRIPTOR' : _STATISTICS,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:Statistics)
  })
_sym_db.RegisterMessage(Statistics)



_ROUTE = _descriptor.ServiceDescriptor(
  name='Route',
  full_name='Route',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=512,
  serialized_end=649,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitialiseAlgorithm',
    full_name='Route.InitialiseAlgorithm',
    index=0,
    containing_service=None,
    input_type=_SELECTION,
    output_type=_STATISTICS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStatistics',
    full_name='Route.GetStatistics',
    index=1,
    containing_service=None,
    input_type=_TMP,
    output_type=_STATISTICS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetHistory',
    full_name='Route.GetHistory',
    index=2,
    containing_service=None,
    input_type=_HISTORYLENGTH,
    output_type=_HISTORY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTE)

DESCRIPTOR.services_by_name['Route'] = _ROUTE

# @@protoc_insertion_point(module_scope)
