# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='route.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0broute.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x12\n\x03Tmp\x12\x0b\n\x03tmp\x18\x01 \x01(\x05\"[\n\tSelection\x12\x10\n\x08Strategy\x18\x01 \x01(\t\x12+\n\nParameters\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0f\n\x07\x43\x61pital\x18\x03 \x01(\x05\"\xf5\x01\n\nStatistics\x12\x0e\n\x06Volume\x18\x01 \x01(\x02\x12\x0c\n\x04Time\x18\x02 \x01(\x02\x12\t\n\x01O\x18\x03 \x01(\x02\x12\t\n\x01H\x18\x04 \x01(\x02\x12\t\n\x01L\x18\x05 \x01(\x02\x12\t\n\x01\x43\x18\x06 \x01(\x02\x12\x0e\n\x06\x61\x63tion\x18\x07 \x01(\x02\x12\x16\n\x0e\x62\x61lance_change\x18\x08 \x01(\x02\x12\r\n\x05stock\x18\t \x01(\x02\x12\x0f\n\x07\x62\x61lance\x18\n \x01(\x02\x12\x0e\n\x06return\x18\x0b \x01(\x02\x12\r\n\x05\x61lpha\x18\x0c \x01(\x02\x12\x0e\n\x06sharpe\x18\r \x01(\x02\x12\x15\n\rannual_sharpe\x18\x0e \x01(\x02\x12\x0f\n\x07sortino\x18\x0f \x01(\x02\x32_\n\x05Route\x12\x30\n\x13InitialiseAlgorithm\x12\n.Selection\x1a\x0b.Statistics\"\x00\x12$\n\rGetStatistics\x12\x04.Tmp\x1a\x0b.Statistics\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_TMP = _descriptor.Descriptor(
  name='Tmp',
  full_name='Tmp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tmp', full_name='Tmp.tmp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=63,
)


_SELECTION = _descriptor.Descriptor(
  name='Selection',
  full_name='Selection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Strategy', full_name='Selection.Strategy', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Parameters', full_name='Selection.Parameters', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Capital', full_name='Selection.Capital', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=156,
)


_STATISTICS = _descriptor.Descriptor(
  name='Statistics',
  full_name='Statistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Volume', full_name='Statistics.Volume', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Time', full_name='Statistics.Time', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='O', full_name='Statistics.O', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='H', full_name='Statistics.H', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='L', full_name='Statistics.L', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='C', full_name='Statistics.C', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='Statistics.action', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance_change', full_name='Statistics.balance_change', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stock', full_name='Statistics.stock', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='Statistics.balance', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return', full_name='Statistics.return', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='Statistics.alpha', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sharpe', full_name='Statistics.sharpe', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='annual_sharpe', full_name='Statistics.annual_sharpe', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sortino', full_name='Statistics.sortino', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=404,
)

_SELECTION.fields_by_name['Parameters'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['Tmp'] = _TMP
DESCRIPTOR.message_types_by_name['Selection'] = _SELECTION
DESCRIPTOR.message_types_by_name['Statistics'] = _STATISTICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tmp = _reflection.GeneratedProtocolMessageType('Tmp', (_message.Message,), {
  'DESCRIPTOR' : _TMP,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:Tmp)
  })
_sym_db.RegisterMessage(Tmp)

Selection = _reflection.GeneratedProtocolMessageType('Selection', (_message.Message,), {
  'DESCRIPTOR' : _SELECTION,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:Selection)
  })
_sym_db.RegisterMessage(Selection)

Statistics = _reflection.GeneratedProtocolMessageType('Statistics', (_message.Message,), {
  'DESCRIPTOR' : _STATISTICS,
  '__module__' : 'route_pb2'
  # @@protoc_insertion_point(class_scope:Statistics)
  })
_sym_db.RegisterMessage(Statistics)



_ROUTE = _descriptor.ServiceDescriptor(
  name='Route',
  full_name='Route',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=406,
  serialized_end=501,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitialiseAlgorithm',
    full_name='Route.InitialiseAlgorithm',
    index=0,
    containing_service=None,
    input_type=_SELECTION,
    output_type=_STATISTICS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStatistics',
    full_name='Route.GetStatistics',
    index=1,
    containing_service=None,
    input_type=_TMP,
    output_type=_STATISTICS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTE)

DESCRIPTOR.services_by_name['Route'] = _ROUTE

# @@protoc_insertion_point(module_scope)
